CREATE DATABASE dragondb;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE, ALTER, DROP ON dragondb.* TO dragon_admin@localhost IDENTIFIED BY 'dragonadmin';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES, LOCK TABLES ON dragondb.* TO dragon_user@localhost IDENTIFIED BY 'dragon';

